const wordToCategoryMap = {
  sports: [
    "cricket",
    "ipl",
    "football",
    "hockey",
    "kabaddi",
    "badminton",
    "tennis",
    "wrestling",
    "olympics",
    "games",
    "chess",
    "kho kho",
    "indian super league",
    "pro kabaddi",
    "commonwealth",
    "asiad",
    "virat",
    "sachin",
  ],
  health: [
    "covid",
    "ayurveda",
    "yoga",
    "hospital",
    "doctor",
    "fitness",
    "medicine",
    "swine flu",
    "healthcare",
    "wellness",
    "allopathy",
    "homeopathy",
    "vaccination",
    "nutrition",
    "diet",
    "corona",
  ],
  technology: [
    "ai",
    "gadgets",
    "software",
    "tech",
    "computer",
    "robotics",
    "startups",
    "apps",
    "smartphones",
    "jio",
    "5g",
    "isro",
    "digital india",
    "electronics",
    "cybersecurity",
    "hacking",
    "gaming",
  ],
  entertainment: [
    "bollywood",
    "movies",
    "cinema",
    "songs",
    "music",
    "web series",
    "hollywood",
    "tollywood",
    "kollywood",
    "tv shows",
    "bigg boss",
    "netflix",
    "prime video",
    "celebrity",
    "box office",
  ],
  business: [
    "sensex",
    "nifty",
    "stock",
    "shares",
    "finance",
    "economy",
    "trade",
    "money",
    "startups",
    "funding",
    "gst",
    "rupee",
    "budget",
    "inflation",
    "ipo",
    "business news",
    "ambani",
    "adani",
    "rbi",
  ],
  science: [
    "isro",
    "space",
    "nasa",
    "moon mission",
    "mars",
    "physics",
    "biology",
    "research",
    "experiment",
    "scientist",
    "agriculture science",
    "nobel",
    "technology innovation",
    "drdo",
    "quantum",
    "genetics",
  ],
  general: [],
};

export default wordToCategoryMap;
